Final commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,22 +8,30 @@ permissions:
 jobs:
   validate:
     runs-on: ubuntu-latest
+    name: packer-build
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
       
-      - name: Validate AMI template
-        run: |
-          # Use Packer to validate the AMI template
-          packer validate  -var-file=./packer/variable.pkrvars.hcl ./packer/aws-ami.pkr.hcl
-        continue-on-error: true
+      - name: Step 5 - Validate Packer Template
+        uses: hashicorp/packer-github-actions@master
+        with:
+          command: validate
+          arguments: -syntax-only
+          target: ./packer/aws-ami.pkr.hcl
+
+      # - name: Validate AMI template
+      #   run: |
+      #     # Use Packer to validate the AMI template
+      #     packer validate  -var-file=./packer/variable.pkrvars.hcl ./packer/aws-ami.pkr.hcl
+      #   continue-on-error: true
       
-      - name: Fail PR status check if template is invalid
-        run: |
-          if [ $? -ne 0 ]; then
-            echo "AMI template is invalid. Please fix the errors and try again."
-            exit 1
-          fi
+#      - name: Fail PR status check if template is invalid
+#        run: |
+#          if [ $? -ne 0 ]; then
+#            echo "AMI template is invalid. Please fix the errors and try again."
+#            exit 1
+#          fi
 
   build:
     runs-on: ubuntu-latest
@@ -57,4 +65,5 @@ jobs:
           command: build
           arguments: "-var-file=./packer/variable.pkrvars.hcl"
           target: ./packer/aws-ami.pkr.hcl
-          
+          env:
+           PACKER_LOG: 1
